language: cpp

sudo: required

compiler:
   - clang
   - g++

os:
   - linux
   - osx
before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install protobuf cmake g++ clang; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then sudo brew update && brew install protobuf clang cmake g++; fi

before_script:
  - mkdir build && cd build && cmake --build /home/rahul/projects/typtopcpp/cmake-build-debug --target tests -- -j 4

script:
  - make tests
