language: cpp

sudo: required

compiler:
   - clang
   - g++

os:
   - linux
   - osx
before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install protobuf-compiler cmake g++ clang; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew reinstall protobuf cmake; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo ./test/create_linux_user.sh tmptyptop hello_pass; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then sudo ./test/create_mac_user.sh tmptyptop hello_pass; fi

before_script:
  - bash .build.sh

script:
  - ./build/test/tests -d yes
