language: cpp

sudo: required

compiler:
   - clang
   - g++

os:
   - linux
   - osx
before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install protobuf-compiler cmake g++ clang; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then if [[ ! $(which cmake) ]]; then brew update && brew install protobuf cmake; fi; fi

before_script:
  - mkdir cmake-build-debug && cd cmake-build-debug && cmake .. && make && cmake .. && make tests && cmake --target tests

script:
  - ./cmake-build-debug/test/tests -d yes
